import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950 p-8">
        {children}
        <footer className="bg-gray-900 p-10 items-start my-5 w-full">
          <p className="text-gray-300 animate-pulse text-sm">Made by: @juanEstebanForeroMontejo</p>
          <p className="text-gray-300 animate-pulse text-sm">Name of page: Math Game</p>
        </footer>
      </body>
    </html>
  );
}
